### ISSUE TITLE
[Feature Request] Able to change route path for "monitoring-panel"

### ISSUE THREAD

**Issue by meesudzu** [MohsenAbrishami/stethoscope#100]
At this moment, the route path for `monitoring-panel` has been fixed, and no way to change It.
It is better to be able to change the route path by adding the prefix, ...
Thank you for your hard work.

**Comment by MohsenAbrishami** [comment]
This issue has been fixed In release 2.2.0. now, you can customize the monitoring panel path in the stethoscope config file
good luck
