### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by dextromethorphanum** [MohsenAbrishami/stethoscope#99]
Nowhere does it say that you have to compile the package firstly. I have error when enter on mysite.com/monitoring-panel - Vite manifest not found at: /var/www/html/public/build/manifest.json.

Also, nowhere in the readme is the url to access the monitoring panel. Very bad.

**Comment by MohsenAbrishami** [comment]
you do not have to compile this package. only you should publish build files. you should run the following command:

php artisan vendor:publish --tag=stethoscope-publish-view

readme updated and thank you for this issue
